# Generated by Django 3.0.3 on 2020-02-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=32)),
            ],
        ),
    ]
