# Generated by Django 3.0.3 on 2020-02-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='birth_date',
            field=models.CharField(max_length=32),
        ),
    ]
