# Generated by Django 3.0.3 on 2020-02-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner_list', '0002_auto_20200216_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
